-- AlterTable
ALTER TABLE "companies" ADD COLUMN     "fg" DECIMAL(12,2) NOT NULL DEFAULT 3.0,
ADD COLUMN     "fpac" DECIMAL(12,2) NOT NULL DEFAULT 0.5,
ADD COLUMN     "fssr" DECIMAL(12,2) NOT NULL DEFAULT 0.3;
