import { createContext, useContext, useState, useEffect } from 'react';
import type { ReactNode } from 'react';

type Language = 'fr' | 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  fr: {
    'app.title': 'ARS Assurance',
    'app.subtitle': 'Simulateur Automobile',
    'common.loading': 'Chargement...',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.close': 'Fermer',
    'common.confirm': 'Confirmer',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.submit': 'Soumettre',
    'common.search': 'Rechercher',
    'common.all': 'Tous',
    'auth.login': 'Connexion',
    'auth.register': 'Inscription',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.logout': 'Déconnexion',
    'nav.dashboard': 'Tableau de bord',
    'nav.newSimulation': 'Nouvelle simulation',
    'nav.simulations': 'Mes simulations',
    'nav.quotes': 'Mes devis',
    'nav.contracts': 'Mes contrats',
    'nav.companies': 'Compagnies',
    'nav.conventions': 'Conventions',
    'nav.guarantees': 'Garanties',
    'nav.pricing': 'Tarification',
    'nav.validation': 'Validation Admin',
    'nav.validationTech': 'Validation Technique',
    'nav.users': 'Utilisateurs',
    'nav.reports': 'Rapports',
    'nav.settings': 'Paramètres',
    'simulation.vehicle': 'Véhicule',
    'simulation.driver': 'Conducteur',
    'simulation.coverage': 'Couverture',
    'simulation.quote': 'Devis',
    'simulation.confirmation': 'Confirmation',
    'quote.number': 'Devis N°',
    'quote.total': 'Montant total',
    'quote.netPremium': 'Prime nette',
    'quote.taxes': 'Taxes',
    'quote.fees': 'Frais',
    'quote.guarantees': 'Garanties',
    'quote.status': 'Statut',
    'quote.client': 'Client',
    'quote.company': 'Compagnie',
    'quote.details': 'Détails',
    'quote.validate': 'Valider',
    'quote.reject': 'Rejeter',
    'quote.createContract': 'Créer contrat',
    'validation.title': 'Validation des devis',
    'validation.subtitle': 'Vérifiez et validez les devis soumis par les clients',
    'validation.clientInfo': 'Informations client',
    'validation.guaranteesIncluded': 'Garanties incluses',
    'document.title': 'Documents justificatifs',
    'document.upload': 'Télécharger',
    'document.type': 'Type de document',
    'document.validated': 'Validé',
    'document.pending': 'En attente',
    'document.none': 'Aucun document téléchargé',
    'toast.validated': 'Devis validé',
    'toast.rejected': 'Devis rejeté',
    'toast.contractCreated': 'Contrat créé',
    'toast.error': 'Erreur',
    'dashboard.title': 'Tableau de bord',
    'dashboard.welcome': 'Bienvenue sur votre espace client',
    'dashboard.adminTitle': 'Tableau de bord administrateur',
    'dashboard.adminSubtitle': 'Vue d\'ensemble de la plateforme',
    'dashboard.newSimulation': 'Nouvelle simulation',
    'dashboard.totalQuotes': 'Total devis',
    'dashboard.drafts': 'Brouillons',
    'dashboard.pending': 'En attente',
    'dashboard.validated': 'Validés',
    'dashboard.users': 'Utilisateurs',
    'dashboard.companies': 'Compagnies',
    'dashboard.quotesGenerated': 'Devis générés',
    'dashboard.recentActivity': 'Activité récente',
    'dashboard.quickActions': 'Actions rapides',
    'dashboard.noActivity': 'Aucune activité récente',
    'simulations.title': 'Mes simulations',
    'simulations.subtitle': 'Gérez vos simulations et devis d\'assurance automobile',
    'simulations.new': 'Nouvelle simulation',
    'simulations.none': 'Aucune simulation',
    'simulations.noneDesc': 'Créez votre première simulation pour obtenir des devis d\'assurance automobile',
    'simulations.create': 'Créer une simulation',
    'simulations.bestQuote': 'Meilleur devis',
    'quotes.title': 'Mes devis',
    'quotes.subtitle': 'Consultez et téléchargez vos devis d\'assurance automobile',
    'quotes.compare': 'Comparer',
    'quotes.none': 'Aucun devis',
    'quotes.noneDesc': 'Créez une simulation pour générer vos premiers devis',
    'quotes.download': 'Télécharger',
    'quotes.guaranteesIncluded': 'Garanties incluses',
    'settings.title': 'Paramètres',
    'settings.subtitle': 'Gérez votre compte et vos préférences',
    'settings.profile': 'Profil',
    'settings.security': 'Sécurité',
    'settings.preferences': 'Préférences',
    'settings.notifications': 'Notifications',
    'settings.personalInfo': 'Informations personnelles',
    'settings.changePassword': 'Changer le mot de passe',
    'settings.displayPreferences': 'Préférences d\'affichage',
    'settings.theme': 'Thème',
    'settings.language': 'Langue',
    'settings.lightMode': 'Mode clair',
    'settings.darkMode': 'Mode sombre',
    'settings.firstName': 'Prénom',
    'settings.lastName': 'Nom',
    'settings.phone': 'Téléphone',
    'settings.currentPassword': 'Mot de passe actuel',
    'settings.newPassword': 'Nouveau mot de passe',
    'settings.confirmPassword': 'Confirmer le mot de passe',
    'settings.saveChanges': 'Enregistrer les modifications',
    'notifications.title': 'Notifications',
    'notifications.subtitle': 'Gérez vos notifications et restez informé des mises à jour importantes',
    'notifications.markAllRead': 'Tout marquer comme lu',
    'notifications.empty': 'Aucune notification',
    'notifications.viewAll': 'Voir toutes les notifications',
    'notifications.markAsRead': 'Marquer comme lu',
    'notifications.new': 'Nouveau',
    'notifications.all': 'Toutes',
    'notifications.unread': 'Non lues',
    'notifications.noUnread': 'Vous n\'avez aucune notification non lue.',
    'notifications.emptyDesc': 'Vous recevrez ici toutes vos notifications importantes.',
    'admin.companies': 'Compagnies d\'Assurance',
    'admin.companiesSubtitle': 'Gérez les compagnies partenaires et leurs conventions',
    'admin.newCompany': 'Nouvelle Compagnie',
    'admin.users': 'Utilisateurs',
    'admin.usersSubtitle': 'Gérez les utilisateurs de la plateforme',
    'admin.pricingRules': 'Règles de tarification',
    'admin.pricingRulesSubtitle': 'Gérez les formules de calcul des primes d\'assurance',
    'admin.newRule': 'Nouvelle règle',
    'admin.allCompanies': 'Toutes les compagnies',
    'admin.allGuarantees': 'Toutes les garanties',
    'admin.active': 'Actif',
    'admin.inactive': 'Inactif',
    'admin.conventions': 'Conventions',
    'admin.quotes': 'Devis',
    'admin.showInactive': 'Afficher les compagnies inactives',
    'common.new': 'Nouveau',
    'common.previous': 'Précédent',
    'common.page': 'Page',
    'common.of': 'sur',
    'common.total': 'total',
    'common.active': 'actives',
    'common.validate': 'à valider',
    'vehicle.title': 'Informations du véhicule',
    'vehicle.subtitle': 'Renseignez les caractéristiques de votre véhicule',
    'vehicle.registration': 'Immatriculation (optionnel)',
    'vehicle.registrationPlaceholder': 'Ex: 12345-A-67',
    'vehicle.fiscalHorsepower': 'Puissance fiscale (CV)',
    'vehicle.horsepowerPlaceholder': 'Ex: 7',
    'vehicle.numberOfSeats': 'Nombre de places',
    'vehicle.seatsPlaceholder': 'Ex: 5',
    'vehicle.firstCirculationDate': 'Date de 1ère mise en circulation',
    'vehicle.newValue': 'Valeur à neuf (DT)',
    'vehicle.newValuePlaceholder': 'Ex: 250000',
    'vehicle.marketValue': 'Valeur vénale (DT)',
    'vehicle.marketValuePlaceholder': 'Ex: 200000',
    'vehicle.marketValueError': 'La valeur vénale ne peut pas dépasser la valeur à neuf',
    'vehicle.tip': 'Conseil : La valeur vénale correspond à la valeur marchande actuelle de votre véhicule.',
    'contracts.title': 'Mes contrats',
    'contracts.subtitle': 'Consultez et gérez vos contrats d\'assurance automobile',
    'contracts.none': 'Aucun contrat',
    'contracts.noneDesc': 'Vos contrats validés apparaîtront ici',
    'notifPrefs.title': 'Préférences de notification',
    'notifPrefs.channels': 'Canaux de notification',
    'notifPrefs.emailNotif': 'Notifications par email',
    'notifPrefs.inAppNotif': 'Notifications dans l\'application',
    'notifPrefs.frequency': 'Fréquence',
    'notifPrefs.immediate': 'Immédiate',
    'notifPrefs.dailyDigest': 'Résumé quotidien',
    'notifPrefs.types': 'Types de notifications',
    'notifPrefs.quoteStatus': 'Statut des devis',
    'notifPrefs.quoteStatusDesc': 'Validation, rejet, création de contrat',
    'notifPrefs.documentRequests': 'Demandes de documents',
    'notifPrefs.documentRequestsDesc': 'Documents requis, rejetés',
    'notifPrefs.paymentReminders': 'Rappels de paiement',
    'notifPrefs.paymentRemindersDesc': 'Échéances, confirmations',
    'notifPrefs.promotionalOffers': 'Offres promotionnelles',
    'notifPrefs.promotionalOffersDesc': 'Réductions, nouveaux produits',
    'notifPrefs.systemAnnouncements': 'Annonces système',
    'notifPrefs.systemAnnouncementsDesc': 'Maintenance, nouvelles fonctionnalités',
  },
  ar: {
    'app.title': 'تأمين ARS',
    'app.subtitle': 'محاكي السيارات',
    'common.loading': 'جاري التحميل...',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.close': 'إغلاق',
    'common.confirm': 'تأكيد',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.submit': 'إرسال',
    'common.search': 'بحث',
    'common.all': 'الكل',
    'auth.login': 'تسجيل الدخول',
    'auth.register': 'التسجيل',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.logout': 'تسجيل الخروج',
    'nav.dashboard': 'لوحة التحكم',
    'nav.newSimulation': 'محاكاة جديدة',
    'nav.simulations': 'محاكاتي',
    'nav.quotes': 'عروض الأسعار',
    'nav.contracts': 'عقودي',
    'nav.companies': 'الشركات',
    'nav.conventions': 'الاتفاقيات',
    'nav.guarantees': 'الضمانات',
    'nav.pricing': 'التسعير',
    'nav.validation': 'التحقق الإداري',
    'nav.validationTech': 'التحقق الفني',
    'nav.users': 'المستخدمون',
    'nav.reports': 'التقارير',
    'nav.settings': 'الإعدادات',
    'simulation.vehicle': 'المركبة',
    'simulation.driver': 'السائق',
    'simulation.coverage': 'التغطية',
    'simulation.quote': 'عرض السعر',
    'simulation.confirmation': 'التأكيد',
    'quote.number': 'رقم العرض',
    'quote.total': 'المبلغ الإجمالي',
    'quote.netPremium': 'القسط الصافي',
    'quote.taxes': 'الضرائب',
    'quote.fees': 'الرسوم',
    'quote.guarantees': 'الضمانات',
    'quote.status': 'الحالة',
    'quote.client': 'العميل',
    'quote.company': 'الشركة',
    'quote.details': 'التفاصيل',
    'quote.validate': 'تأكيد',
    'quote.reject': 'رفض',
    'quote.createContract': 'إنشاء عقد',
    'validation.title': 'التحقق من عروض الأسعار',
    'validation.subtitle': 'تحقق وصادق على عروض الأسعار المقدمة من العملاء',
    'validation.clientInfo': 'معلومات العميل',
    'validation.guaranteesIncluded': 'الضمانات المشمولة',
    'document.title': 'المستندات المطلوبة',
    'document.upload': 'تحميل',
    'document.type': 'نوع المستند',
    'document.validated': 'تم التحقق',
    'document.pending': 'قيد الانتظار',
    'document.none': 'لا توجد مستندات',
    'toast.validated': 'تم التحقق من العرض',
    'toast.rejected': 'تم رفض العرض',
    'toast.contractCreated': 'تم إنشاء العقد',
    'toast.error': 'خطأ',
    'dashboard.title': 'لوحة التحكم',
    'dashboard.welcome': 'مرحبا بك في مساحتك',
    'dashboard.adminTitle': 'لوحة تحكم المسؤول',
    'dashboard.adminSubtitle': 'نظرة عامة على المنصة',
    'dashboard.newSimulation': 'محاكاة جديدة',
    'dashboard.totalQuotes': 'إجمالي العروض',
    'dashboard.drafts': 'مسودات',
    'dashboard.pending': 'قيد الانتظار',
    'dashboard.validated': 'معتمد',
    'dashboard.users': 'المستخدمون',
    'dashboard.companies': 'الشركات',
    'dashboard.quotesGenerated': 'عروض منشأة',
    'dashboard.recentActivity': 'النشاط الأخير',
    'dashboard.quickActions': 'إجراءات سريعة',
    'dashboard.noActivity': 'لا يوجد نشاط حديث',
    'simulations.title': 'محاكاتي',
    'simulations.subtitle': 'إدارة محاكاتك وعروض التأمين',
    'simulations.new': 'محاكاة جديدة',
    'simulations.none': 'لا توجد محاكاة',
    'simulations.noneDesc': 'أنشئ محاكاتك الأولى للحصول على عروض التأمين',
    'simulations.create': 'إنشاء محاكاة',
    'simulations.bestQuote': 'أفضل عرض',
    'quotes.title': 'عروض الأسعار',
    'quotes.subtitle': 'عرض وتحميل عروض التأمين',
    'quotes.compare': 'مقارنة',
    'quotes.none': 'لا توجد عروض',
    'quotes.noneDesc': 'أنشئ محاكاة للحصول على عروضك الأولى',
    'quotes.download': 'تحميل',
    'quotes.guaranteesIncluded': 'الضمانات المشمولة',
    'settings.title': 'الإعدادات',
    'settings.subtitle': 'إدارة حسابك وتفضيلاتك',
    'settings.profile': 'الملف الشخصي',
    'settings.security': 'الأمان',
    'settings.preferences': 'التفضيلات',
    'settings.notifications': 'الإشعارات',
    'settings.personalInfo': 'المعلومات الشخصية',
    'settings.changePassword': 'تغيير كلمة المرور',
    'settings.displayPreferences': 'تفضيلات العرض',
    'settings.theme': 'المظهر',
    'settings.language': 'اللغة',
    'settings.lightMode': 'الوضع الفاتح',
    'settings.darkMode': 'الوضع الداكن',
    'settings.firstName': 'الاسم الأول',
    'settings.lastName': 'الاسم الأخير',
    'settings.phone': 'الهاتف',
    'settings.currentPassword': 'كلمة المرور الحالية',
    'settings.newPassword': 'كلمة المرور الجديدة',
    'settings.confirmPassword': 'تأكيد كلمة المرور',
    'settings.saveChanges': 'حفظ التغييرات',
    'notifications.title': 'الإشعارات',
    'notifications.subtitle': 'إدارة إشعاراتك والبقاء على اطلاع',
    'notifications.markAllRead': 'تحديد الكل كمقروء',
    'notifications.empty': 'لا توجد إشعارات',
    'notifications.viewAll': 'عرض جميع الإشعارات',
    'notifications.markAsRead': 'تحديد كمقروء',
    'notifications.new': 'جديد',
    'notifications.all': 'الكل',
    'notifications.unread': 'غير مقروءة',
    'notifications.noUnread': 'ليس لديك إشعارات غير مقروءة.',
    'notifications.emptyDesc': 'ستتلقى هنا جميع إشعاراتك المهمة.',
    'admin.companies': 'شركات التأمين',
    'admin.companiesSubtitle': 'إدارة الشركات الشريكة',
    'admin.newCompany': 'شركة جديدة',
    'admin.users': 'المستخدمون',
    'admin.usersSubtitle': 'إدارة مستخدمي المنصة',
    'admin.pricingRules': 'قواعد التسعير',
    'admin.pricingRulesSubtitle': 'إدارة صيغ حساب الأقساط',
    'admin.newRule': 'قاعدة جديدة',
    'admin.allCompanies': 'جميع الشركات',
    'admin.allGuarantees': 'جميع الضمانات',
    'admin.active': 'نشط',
    'admin.inactive': 'غير نشط',
    'admin.conventions': 'الاتفاقيات',
    'admin.quotes': 'عروض',
    'admin.showInactive': 'عرض الشركات غير النشطة',
    'common.new': 'جديد',
    'common.previous': 'السابق',
    'common.page': 'صفحة',
    'common.of': 'من',
    'common.total': 'إجمالي',
    'common.active': 'نشطة',
    'common.validate': 'للتحقق',
    'vehicle.title': 'معلومات المركبة',
    'vehicle.subtitle': 'أدخل خصائص مركبتك',
    'vehicle.registration': 'رقم التسجيل (اختياري)',
    'vehicle.registrationPlaceholder': 'مثال: 12345-A-67',
    'vehicle.fiscalHorsepower': 'القوة الضريبية (CV)',
    'vehicle.horsepowerPlaceholder': 'مثال: 7',
    'vehicle.numberOfSeats': 'عدد المقاعد',
    'vehicle.seatsPlaceholder': 'مثال: 5',
    'vehicle.firstCirculationDate': 'تاريخ أول تشغيل',
    'vehicle.newValue': 'القيمة الجديدة (DT)',
    'vehicle.newValuePlaceholder': 'مثال: 250000',
    'vehicle.marketValue': 'القيمة السوقية (DT)',
    'vehicle.marketValuePlaceholder': 'مثال: 200000',
    'vehicle.marketValueError': 'لا يمكن أن تتجاوز القيمة السوقية القيمة الجديدة',
    'vehicle.tip': 'نصيحة: القيمة السوقية تعني القيمة الحالية لمركبتك في السوق.',
    'contracts.title': 'عقودي',
    'contracts.subtitle': 'عرض وإدارة عقود التأمين',
    'contracts.none': 'لا توجد عقود',
    'contracts.noneDesc': 'ستظهر عقودك المعتمدة هنا',
    'notifPrefs.title': 'تفضيلات الإشعارات',
    'notifPrefs.channels': 'قنوات الإشعارات',
    'notifPrefs.emailNotif': 'إشعارات البريد',
    'notifPrefs.inAppNotif': 'إشعارات التطبيق',
    'notifPrefs.frequency': 'التكرار',
    'notifPrefs.immediate': 'فوري',
    'notifPrefs.dailyDigest': 'ملخص يومي',
    'notifPrefs.types': 'أنواع الإشعارات',
    'notifPrefs.quoteStatus': 'حالة العروض',
    'notifPrefs.quoteStatusDesc': 'التحقق، الرفض، إنشاء عقد',
    'notifPrefs.documentRequests': 'طلبات المستندات',
    'notifPrefs.documentRequestsDesc': 'مستندات مطلوبة، مرفوضة',
    'notifPrefs.paymentReminders': 'تذكيرات الدفع',
    'notifPrefs.paymentRemindersDesc': 'مواعيد، تأكيدات',
    'notifPrefs.promotionalOffers': 'عروض ترويجية',
    'notifPrefs.promotionalOffersDesc': 'خصومات، منتجات جديدة',
    'notifPrefs.systemAnnouncements': 'إعلانات النظام',
    'notifPrefs.systemAnnouncementsDesc': 'صيانة، ميزات جديدة',
  },
  en: {
    'app.title': 'ARS Insurance',
    'app.subtitle': 'Auto Simulator',
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.submit': 'Submit',
    'common.search': 'Search',
    'common.all': 'All',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.logout': 'Logout',
    'nav.dashboard': 'Dashboard',
    'nav.newSimulation': 'New Simulation',
    'nav.simulations': 'My Simulations',
    'nav.quotes': 'My Quotes',
    'nav.contracts': 'My Contracts',
    'nav.companies': 'Companies',
    'nav.conventions': 'Conventions',
    'nav.guarantees': 'Guarantees',
    'nav.pricing': 'Pricing',
    'nav.validation': 'Admin Validation',
    'nav.validationTech': 'Technical Validation',
    'nav.users': 'Users',
    'nav.reports': 'Reports',
    'nav.settings': 'Settings',
    'simulation.vehicle': 'Vehicle',
    'simulation.driver': 'Driver',
    'simulation.coverage': 'Coverage',
    'simulation.quote': 'Quote',
    'simulation.confirmation': 'Confirmation',
    'quote.number': 'Quote No.',
    'quote.total': 'Total Amount',
    'quote.netPremium': 'Net Premium',
    'quote.taxes': 'Taxes',
    'quote.fees': 'Fees',
    'quote.guarantees': 'Guarantees',
    'quote.status': 'Status',
    'quote.client': 'Client',
    'quote.company': 'Company',
    'quote.details': 'Details',
    'quote.validate': 'Validate',
    'quote.reject': 'Reject',
    'quote.createContract': 'Create Contract',
    'validation.title': 'Quote Validation',
    'validation.subtitle': 'Review and validate quotes submitted by clients',
    'validation.clientInfo': 'Client Information',
    'validation.guaranteesIncluded': 'Included Guarantees',
    'document.title': 'Supporting Documents',
    'document.upload': 'Upload',
    'document.type': 'Document Type',
    'document.validated': 'Validated',
    'document.pending': 'Pending',
    'document.none': 'No documents uploaded',
    'toast.validated': 'Quote validated',
    'toast.rejected': 'Quote rejected',
    'toast.contractCreated': 'Contract created',
    'toast.error': 'Error',
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome to your client space',
    'dashboard.adminTitle': 'Administrator Dashboard',
    'dashboard.adminSubtitle': 'Platform Overview',
    'dashboard.newSimulation': 'New Simulation',
    'dashboard.totalQuotes': 'Total Quotes',
    'dashboard.drafts': 'Drafts',
    'dashboard.pending': 'Pending',
    'dashboard.validated': 'Validated',
    'dashboard.users': 'Users',
    'dashboard.companies': 'Companies',
    'dashboard.quotesGenerated': 'Quotes Generated',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.noActivity': 'No recent activity',
    'simulations.title': 'My Simulations',
    'simulations.subtitle': 'Manage your simulations and insurance quotes',
    'simulations.new': 'New Simulation',
    'simulations.none': 'No simulations',
    'simulations.noneDesc': 'Create your first simulation to get insurance quotes',
    'simulations.create': 'Create Simulation',
    'simulations.bestQuote': 'Best Quote',
    'quotes.title': 'My Quotes',
    'quotes.subtitle': 'View and download your insurance quotes',
    'quotes.compare': 'Compare',
    'quotes.none': 'No quotes',
    'quotes.noneDesc': 'Create a simulation to generate your first quotes',
    'quotes.download': 'Download',
    'quotes.guaranteesIncluded': 'Included Guarantees',
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account and preferences',
    'settings.profile': 'Profile',
    'settings.security': 'Security',
    'settings.preferences': 'Preferences',
    'settings.notifications': 'Notifications',
    'settings.personalInfo': 'Personal Information',
    'settings.changePassword': 'Change Password',
    'settings.displayPreferences': 'Display Preferences',
    'settings.theme': 'Theme',
    'settings.language': 'Language',
    'settings.lightMode': 'Light Mode',
    'settings.darkMode': 'Dark Mode',
    'settings.firstName': 'First Name',
    'settings.lastName': 'Last Name',
    'settings.phone': 'Phone',
    'settings.currentPassword': 'Current Password',
    'settings.newPassword': 'New Password',
    'settings.confirmPassword': 'Confirm Password',
    'settings.saveChanges': 'Save Changes',
    'notifications.title': 'Notifications',
    'notifications.subtitle': 'Manage your notifications and stay informed',
    'notifications.markAllRead': 'Mark all as read',
    'notifications.empty': 'No notifications',
    'notifications.viewAll': 'View all notifications',
    'notifications.markAsRead': 'Mark as read',
    'notifications.new': 'New',
    'notifications.all': 'All',
    'notifications.unread': 'Unread',
    'notifications.noUnread': 'You have no unread notifications.',
    'notifications.emptyDesc': 'You will receive all your important notifications here.',
    'admin.companies': 'Insurance Companies',
    'admin.companiesSubtitle': 'Manage partner companies and their conventions',
    'admin.newCompany': 'New Company',
    'admin.users': 'Users',
    'admin.usersSubtitle': 'Manage platform users',
    'admin.pricingRules': 'Pricing Rules',
    'admin.pricingRulesSubtitle': 'Manage premium calculation formulas',
    'admin.newRule': 'New Rule',
    'admin.allCompanies': 'All Companies',
    'admin.allGuarantees': 'All Guarantees',
    'admin.active': 'Active',
    'admin.inactive': 'Inactive',
    'admin.conventions': 'Conventions',
    'admin.quotes': 'Quotes',
    'admin.showInactive': 'Show inactive companies',
    'common.new': 'New',
    'common.previous': 'Previous',
    'common.page': 'Page',
    'common.of': 'of',
    'common.total': 'total',
    'common.active': 'active',
    'common.validate': 'to validate',
    'vehicle.title': 'Vehicle Information',
    'vehicle.subtitle': 'Enter your vehicle characteristics',
    'vehicle.registration': 'Registration (optional)',
    'vehicle.registrationPlaceholder': 'Ex: 12345-A-67',
    'vehicle.fiscalHorsepower': 'Fiscal Horsepower (HP)',
    'vehicle.horsepowerPlaceholder': 'Ex: 7',
    'vehicle.numberOfSeats': 'Number of Seats',
    'vehicle.seatsPlaceholder': 'Ex: 5',
    'vehicle.firstCirculationDate': 'First Registration Date',
    'vehicle.newValue': 'New Value (DT)',
    'vehicle.newValuePlaceholder': 'Ex: 250000',
    'vehicle.marketValue': 'Market Value (DT)',
    'vehicle.marketValuePlaceholder': 'Ex: 200000',
    'vehicle.marketValueError': 'Market value cannot exceed new value',
    'vehicle.tip': 'Tip: Market value corresponds to the current market value of your vehicle.',
    'contracts.title': 'My Contracts',
    'contracts.subtitle': 'View and manage your insurance contracts',
    'contracts.none': 'No contracts',
    'contracts.noneDesc': 'Your validated contracts will appear here',
    'notifPrefs.title': 'Notification Preferences',
    'notifPrefs.channels': 'Notification Channels',
    'notifPrefs.emailNotif': 'Email Notifications',
    'notifPrefs.inAppNotif': 'In-App Notifications',
    'notifPrefs.frequency': 'Frequency',
    'notifPrefs.immediate': 'Immediate',
    'notifPrefs.dailyDigest': 'Daily Digest',
    'notifPrefs.types': 'Notification Types',
    'notifPrefs.quoteStatus': 'Quote Status',
    'notifPrefs.quoteStatusDesc': 'Validation, rejection, contract creation',
    'notifPrefs.documentRequests': 'Document Requests',
    'notifPrefs.documentRequestsDesc': 'Required documents, rejected',
    'notifPrefs.paymentReminders': 'Payment Reminders',
    'notifPrefs.paymentRemindersDesc': 'Due dates, confirmations',
    'notifPrefs.promotionalOffers': 'Promotional Offers',
    'notifPrefs.promotionalOffersDesc': 'Discounts, new products',
    'notifPrefs.systemAnnouncements': 'System Announcements',
    'notifPrefs.systemAnnouncementsDesc': 'Maintenance, new features',
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'fr';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
